apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://congressional-data-api-1066017671167.us-central1.run.app","https://congressional-data-api-yovvxn4y7q-uc.a.run.app"]'
  labels:
    cloud.googleapis.com/location: us-central1
  name: congressional-data-api
  namespace: '1066017671167'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 527.0.0
        run.googleapis.com/cloudsql-instances: chefgavin:us-central1:congressional-db
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: omfcrfdlcl
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: SECRET_KEY
          value: your-secret-key-here
        - name: DATABASE_URL
          value: postgresql+psycopg2://postgres:Noel19922024@/cloudsql/chefgavin:us-central1:congressional-db/congress_data
        - name: CONGRESS_API_KEY
          value: oM8IsuU5VfUiVsrMbUBNgYLpz2F2lUZEkTygiZik
        - name: GCP_PROJECT_ID
          value: chefgavin
        image: gcr.io/chefgavin/congressional-data-api:simple-fix
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 1066017671167-compute@developer.gserviceaccount.com
      timeoutSeconds: 3600
  traffic:
  - latestRevision: true
    percent: 100
