version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: congress_data
      POSTGRES_USER: congress_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U congress_user -d congress_data"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://congress_user:password@db:5432/congress_data
      - CONGRESS_API_KEY=oM8IsuU5VfUiVsrMbUBNgYLpz2F2lUZEkTygiZik
      - SECRET_KEY=h6HkF&2xJv8tPw@Q$$NuR9cV#mB5zKdLf!A@pXs4Y*nG7oE&hWq
      - DEBUG=true
      - REDIS_URL=redis://redis:6379
      - ALLOWED_ORIGINS=["http://localhost:3000","http://localhost:8080"]
      - LOG_LEVEL=INFO
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: