-- Update hearing committee assignments
-- Generated by hearing_committee_matcher.py

-- Update hearing: Armed Services
Subcommittee on Airland
UPDATE hearings SET committee_id = 134 WHERE id = 120;

-- Update hearing: Armed Services
Subcommittee on Emerging Threats and Capabilities
UPDATE hearings SET committee_id = 134 WHERE id = 121;

-- Update hearing: Armed Services
Subcommittee on Personnel
UPDATE hearings SET committee_id = 134 WHERE id = 122;

-- Update hearing: Armed Services
Subcommittee on Readiness and Management Support
UPDATE hearings SET committee_id = 134 WHERE id = 123;

-- Update hearing: Armed Services
Subcommittee on Cybersecurity
UPDATE hearings SET committee_id = 134 WHERE id = 124;

-- Update hearing: Armed Services
Subcommittee on Strategic Forces
UPDATE hearings SET committee_id = 134 WHERE id = 125;

-- Update hearing: Armed Services
Subcommittee on Seapower
UPDATE hearings SET committee_id = 134 WHERE id = 126;

-- Update hearing: Armed Services
UPDATE hearings SET committee_id = 134 WHERE id = 127;

-- Update hearing: Intelligence
UPDATE hearings SET committee_id = 41 WHERE id = 128;

-- Update hearing: Environment and Public Works
UPDATE hearings SET committee_id = 163 WHERE id = 129;

-- Update hearing: Armed Services
UPDATE hearings SET committee_id = 134 WHERE id = 130;

-- Update hearing: Energy and Natural Resources
UPDATE hearings SET committee_id = 163 WHERE id = 131;

-- Update hearing: Health, Education, Labor, and Pensions
UPDATE hearings SET committee_id = 174 WHERE id = 132;

-- Update hearing: Appropriations
UPDATE hearings SET committee_id = 121 WHERE id = 133;

-- Update hearing: Commerce, Science, and Transportation
UPDATE hearings SET committee_id = 2 WHERE id = 134;

-- Update hearing: Foreign Relations
UPDATE hearings SET committee_id = 173 WHERE id = 135;

-- Update hearing: Health, Education, Labor, and Pensions
UPDATE hearings SET committee_id = 174 WHERE id = 136;

-- Update hearing: Banking, Housing, and Urban Affairs
UPDATE hearings SET committee_id = 142 WHERE id = 137;

-- Update hearing: Intelligence
UPDATE hearings SET committee_id = 41 WHERE id = 138;

-- Update hearing: Armed Services
UPDATE hearings SET committee_id = 134 WHERE id = 139;

-- Update hearing: Appropriations
UPDATE hearings SET committee_id = 121 WHERE id = 140;

-- Update hearing: Energy and Natural Resources
UPDATE hearings SET committee_id = 163 WHERE id = 141;

-- Update hearing: Intelligence
UPDATE hearings SET committee_id = 41 WHERE id = 142;

-- Update hearing: Armed Services
UPDATE hearings SET committee_id = 134 WHERE id = 143;

-- Update hearing: Armed Services
Subcommittee on Airland
UPDATE hearings SET committee_id = 134 WHERE id = 167;

-- Update hearing: Armed Services
Subcommittee on Emerging Threats and Capabilities
UPDATE hearings SET committee_id = 134 WHERE id = 168;

-- Update hearing: Armed Services
Subcommittee on Personnel
UPDATE hearings SET committee_id = 134 WHERE id = 169;

-- Update hearing: Armed Services
Subcommittee on Readiness and Management Support
UPDATE hearings SET committee_id = 134 WHERE id = 170;

-- Update hearing: Armed Services
Subcommittee on Cybersecurity
UPDATE hearings SET committee_id = 134 WHERE id = 171;

-- Update hearing: Armed Services
Subcommittee on Strategic Forces
UPDATE hearings SET committee_id = 134 WHERE id = 172;

-- Update hearing: Armed Services
Subcommittee on Seapower
UPDATE hearings SET committee_id = 134 WHERE id = 173;

-- Update hearing: Armed Services
UPDATE hearings SET committee_id = 134 WHERE id = 174;

-- Update hearing: Appropriations
UPDATE hearings SET committee_id = 121 WHERE id = 318;

-- Update hearing: Intelligence
UPDATE hearings SET committee_id = 41 WHERE id = 175;

-- Update hearing: Environment and Public Works
UPDATE hearings SET committee_id = 163 WHERE id = 176;

-- Update hearing: Armed Services
UPDATE hearings SET committee_id = 134 WHERE id = 177;

-- Update hearing: Energy and Natural Resources
UPDATE hearings SET committee_id = 163 WHERE id = 178;

-- Update hearing: Health, Education, Labor, and Pensions
UPDATE hearings SET committee_id = 174 WHERE id = 179;

-- Update hearing: Appropriations
UPDATE hearings SET committee_id = 121 WHERE id = 180;

-- Update hearing: Commerce, Science, and Transportation
UPDATE hearings SET committee_id = 2 WHERE id = 181;

-- Update hearing: Foreign Relations
UPDATE hearings SET committee_id = 173 WHERE id = 182;

-- Update hearing: Health, Education, Labor, and Pensions
UPDATE hearings SET committee_id = 174 WHERE id = 183;

-- Update hearing: Banking, Housing, and Urban Affairs
UPDATE hearings SET committee_id = 142 WHERE id = 184;

-- Update hearing: Intelligence
UPDATE hearings SET committee_id = 41 WHERE id = 185;

-- Update hearing: Armed Services
UPDATE hearings SET committee_id = 134 WHERE id = 186;

-- Update hearing: Appropriations
UPDATE hearings SET committee_id = 121 WHERE id = 187;

-- Update hearing: Energy and Natural Resources
UPDATE hearings SET committee_id = 163 WHERE id = 188;

-- Update hearing: Intelligence
UPDATE hearings SET committee_id = 41 WHERE id = 189;

-- Update hearing: Armed Services
UPDATE hearings SET committee_id = 134 WHERE id = 190;

-- Update hearing: Armed Services
Subcommittee on Airland
UPDATE hearings SET committee_id = 134 WHERE id = 214;

-- Update hearing: Armed Services
Subcommittee on Emerging Threats and Capabilities
UPDATE hearings SET committee_id = 134 WHERE id = 215;

-- Update hearing: Armed Services
Subcommittee on Personnel
UPDATE hearings SET committee_id = 134 WHERE id = 216;

-- Update hearing: Armed Services
Subcommittee on Readiness and Management Support
UPDATE hearings SET committee_id = 134 WHERE id = 217;

-- Update hearing: Armed Services
Subcommittee on Cybersecurity
UPDATE hearings SET committee_id = 134 WHERE id = 218;

-- Update hearing: Armed Services
Subcommittee on Strategic Forces
UPDATE hearings SET committee_id = 134 WHERE id = 219;

-- Update hearing: Armed Services
Subcommittee on Seapower
UPDATE hearings SET committee_id = 134 WHERE id = 220;

-- Update hearing: Armed Services
UPDATE hearings SET committee_id = 134 WHERE id = 221;

-- Update hearing: Intelligence
UPDATE hearings SET committee_id = 41 WHERE id = 222;

-- Update hearing: Environment and Public Works
UPDATE hearings SET committee_id = 163 WHERE id = 223;

-- Update hearing: Armed Services
UPDATE hearings SET committee_id = 134 WHERE id = 224;

-- Update hearing: Energy and Natural Resources
UPDATE hearings SET committee_id = 163 WHERE id = 225;

-- Update hearing: Health, Education, Labor, and Pensions
UPDATE hearings SET committee_id = 174 WHERE id = 226;

-- Update hearing: Appropriations
UPDATE hearings SET committee_id = 121 WHERE id = 227;

-- Update hearing: Commerce, Science, and Transportation
UPDATE hearings SET committee_id = 2 WHERE id = 228;

-- Update hearing: Foreign Relations
UPDATE hearings SET committee_id = 173 WHERE id = 229;

-- Update hearing: Health, Education, Labor, and Pensions
UPDATE hearings SET committee_id = 174 WHERE id = 230;

-- Update hearing: Banking, Housing, and Urban Affairs
UPDATE hearings SET committee_id = 142 WHERE id = 231;

-- Update hearing: Intelligence
UPDATE hearings SET committee_id = 41 WHERE id = 232;

-- Update hearing: Armed Services
UPDATE hearings SET committee_id = 134 WHERE id = 233;

-- Update hearing: Appropriations
UPDATE hearings SET committee_id = 121 WHERE id = 234;

-- Update hearing: Energy and Natural Resources
UPDATE hearings SET committee_id = 163 WHERE id = 235;

-- Update hearing: Intelligence
UPDATE hearings SET committee_id = 41 WHERE id = 236;

-- Update hearing: Armed Services
UPDATE hearings SET committee_id = 134 WHERE id = 237;

-- Update hearing: Armed Services
Subcommittee on Airland
UPDATE hearings SET committee_id = 134 WHERE id = 260;

-- Update hearing: Armed Services
Subcommittee on Emerging Threats and Capabilities
UPDATE hearings SET committee_id = 134 WHERE id = 261;

-- Update hearing: Armed Services
Subcommittee on Personnel
UPDATE hearings SET committee_id = 134 WHERE id = 262;

-- Update hearing: Armed Services
Subcommittee on Readiness and Management Support
UPDATE hearings SET committee_id = 134 WHERE id = 263;

-- Update hearing: Armed Services
Subcommittee on Cybersecurity
UPDATE hearings SET committee_id = 134 WHERE id = 264;

-- Update hearing: Armed Services
Subcommittee on Strategic Forces
UPDATE hearings SET committee_id = 134 WHERE id = 265;

-- Update hearing: Armed Services
Subcommittee on Seapower
UPDATE hearings SET committee_id = 134 WHERE id = 266;

-- Update hearing: Armed Services
UPDATE hearings SET committee_id = 134 WHERE id = 267;

-- Update hearing: Intelligence
UPDATE hearings SET committee_id = 41 WHERE id = 268;

-- Update hearing: Environment and Public Works
UPDATE hearings SET committee_id = 163 WHERE id = 269;

-- Update hearing: Armed Services
UPDATE hearings SET committee_id = 134 WHERE id = 270;

-- Update hearing: Energy and Natural Resources
UPDATE hearings SET committee_id = 163 WHERE id = 271;

-- Update hearing: Health, Education, Labor, and Pensions
UPDATE hearings SET committee_id = 174 WHERE id = 272;

-- Update hearing: Appropriations
UPDATE hearings SET committee_id = 121 WHERE id = 273;

-- Update hearing: Commerce, Science, and Transportation
UPDATE hearings SET committee_id = 2 WHERE id = 274;

-- Update hearing: Foreign Relations
UPDATE hearings SET committee_id = 173 WHERE id = 275;

-- Update hearing: Health, Education, Labor, and Pensions
UPDATE hearings SET committee_id = 174 WHERE id = 276;

-- Update hearing: Banking, Housing, and Urban Affairs
UPDATE hearings SET committee_id = 142 WHERE id = 277;

-- Update hearing: Intelligence
UPDATE hearings SET committee_id = 41 WHERE id = 278;

-- Update hearing: Armed Services
UPDATE hearings SET committee_id = 134 WHERE id = 279;

-- Update hearing: Appropriations
UPDATE hearings SET committee_id = 121 WHERE id = 280;

-- Update hearing: Energy and Natural Resources
UPDATE hearings SET committee_id = 163 WHERE id = 281;

-- Update hearing: Intelligence
UPDATE hearings SET committee_id = 41 WHERE id = 282;

-- Update hearing: Armed Services
UPDATE hearings SET committee_id = 134 WHERE id = 283;

-- Create index for committee queries
CREATE INDEX IF NOT EXISTS idx_hearings_committee_id ON hearings(committee_id);
