steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/chefgavin/congress-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/chefgavin/congress-api:latest'
      - '.'
    dir: 'backend'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/chefgavin/congress-api:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/chefgavin/congress-api:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'congressional-data-api'
      - '--image'
      - 'gcr.io/chefgavin/congress-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'DEBUG=false'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=chefgavin'

images:
  - 'gcr.io/chefgavin/congress-api:$COMMIT_SHA'
  - 'gcr.io/chefgavin/congress-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY