# Google Cloud Build configuration for Congressional Data API Service
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/congressional-api:${SHORT_SHA}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/congressional-api:latest'
      - '-f'
      - 'Dockerfile.optimized'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/congressional-api:${SHORT_SHA}'

  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/congressional-api:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'congressional-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/congressional-api:${SHORT_SHA}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8003'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '2'
      - '--concurrency'
      - '100'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'
      - '--timeout'
      - '900'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,LOG_LEVEL=INFO,DEBUG=false,API_HOST=0.0.0.0,API_PORT=8003,UVICORN_WORKERS=4,DATABASE_POOL_SIZE=20,CACHE_ENABLED=true,METRICS_ENABLED=true,SECURITY_HEADERS_ENABLED=true,LOG_FORMAT=json'
      - '--set-secrets'
      - 'DATABASE_URL=congressional-db-url:latest,SECRET_KEY=congressional-secret-key:latest,REDIS_URL=congressional-redis-url:latest'

# Configure build triggers
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Define substitutions
substitutions:
  _SERVICE_NAME: 'congressional-api'
  _REGION: 'us-central1'

# Timeout for the entire build
timeout: '1200s'

# Build tags
tags:
  - 'congressional-api'
  - 'production'
  - '${SHORT_SHA}'