version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: congressional_db
    environment:
      POSTGRES_USER: congress_user
      POSTGRES_PASSWORD: congress_pass
      POSTGRES_DB: congress_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U congress_user -d congress_data"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis cache
  redis:
    image: redis:7-alpine
    container_name: congressional_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: congressional_api
    environment:
      DATABASE_URL: postgresql://congress_user:congress_pass@postgres:5432/congress_data
      REDIS_URL: redis://redis:6379/0
      ENVIRONMENT: development
      LOG_LEVEL: INFO
      API_HOST: 0.0.0.0
      API_PORT: 8003
      DEBUG: true
    ports:
      - "8003:8003"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./api:/app/api:ro
      - ./main.py:/app/main.py:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development service (with auto-reload)
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: congressional_api_dev
    environment:
      DATABASE_URL: postgresql://congress_user:congress_pass@postgres:5432/congress_data
      REDIS_URL: redis://redis:6379/0
      ENVIRONMENT: development
      LOG_LEVEL: DEBUG
      API_HOST: 0.0.0.0
      API_PORT: 8003
      DEBUG: true
    ports:
      - "8004:8003"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["python", "main.py", "dev"]
    profiles:
      - dev

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: congressional_network